### ISSUE TITLE
Issue with ATTiny841

### ISSUE THREAD

**Issue by DatanoiseTV** [tadfmac/mi-muz#2]
Hello,

I cannot get this to work with an ATTiny841 with internal oscillator (8 MHz), which is known to work for V-USB with 8 MHz (see Micronucleus Bootloader).

Can you help?

Thanks

**Comment by tadfmac** [comment]
Hi,

V-USB does not support 8Mhz, it should need over 12Mhz.

https://www.obdev.at/products/vusb/index.html

And mi:muz firmware is now only support 16 mhz on ATtiny841.

Thanks.

**Comment by DatanoiseTV** [comment]
Ok,

Same issue with Attiny85 with 16.5 MHz, unfortunately.

Thanks
