### ISSUE TITLE
mi:muz:tuch v0.20 operation check result

### ISSUE THREAD

**Issue by tadfmac** [tadfmac/mi-muz#6]
# Operation check result

| PC Name | OS Version | Host Connector Type | Host USB Version | USB Hub | Date | Result |
| :-- | :-- | :-- | :-- | :-- | :-- | --: |
| Apple MacBook Air 11inch Mid 2013 | MacOSX 10.8.4 | USB Type A | USB 3.0 | None | 2016.09.8 | OK |
| Apple MacBook Air 11inch Mid 2013 | MacOSX 10.8.4 | USB Type A | USB 3.0 | Green House GH-UH204SBK L000/1550 (USB 2.0) | 2016.09.8 | OK |
| Apple MacBook Pro 13inch Late 2015 | MacOSX 10.11.1 | USB Type A | USB 3.0 | None | 2016.09.8 | OK |
| Apple MacBook Air 11inch Mid 2013 | MacOSX 10.12.0 | USB Type A | USB 3.0 | None | 2016.09.12 | OK |
| Apple MacBook Air 11inch Mid 2013 | MacOSX 10.12.0 | USB Type A | USB 3.0 | Green House GH-UH204SBK L000/1550 (USB 2.0) | 2016.09.12 | OK |
| DELL PC | Windows 7 | USB Type A | USB 3.0 | None | 2016.09.9 | OK |
| Microsoft Surface Pro 3 | Windows 10 | USB Type A | USB 3.0 | None | 2016.09.12 | OK |
| Apple MacBook Retina 12inch Early 2016 | MacOSX 10.? | USB Type C | USB 3.1 Gen.1 | [AuKey CB-C25](https://www.amazon.co.jp/gp/product/B01DCZMDJ0/ref=oh_aui_detailpage_o02_s00) | 2016.09.8 | NG |

**Comment by hsgw** [comment]
| PC Name | OS Version | Host Connector Type | Host USB Version | USB Hub | Date | Result |
| --- | --- | --- | --- | --- | --- | --- |
| thinkpad x230 | Windows10 | USB Type A | USB 3.0 | None | 2016.10.06 | NG (remove DP pullup) |
| thinkpad x230 | Windows10 | USB Type A | USB 3.0 | Elecom USB2.0 Hub | 2016.10.06 | OK (remove DP pullup) |
| Raspberry Pi 3 | Raspbian Jessie lite kernel 4.4 | USB Type A | USB 2.0 | None | 2016.10.06 | OK (remove DP pullup) |

**Comment by tadfmac** [comment]
こちらに移します。
https://github.com/tadfmac/mi-muz/wiki/connection-list
